### ISSUE TITLE
Parallelize integration tests

### ISSUE THREAD

**Issue by shaneutt** [kubernetes-sigs/blixt#100]
Our current integration test suite operates serially running each test case one-by-one. Ideally we should parallelize it to save time during testing. This could also help in sounding the alarm if we ever have bugs in parallel operations.

```[tasklist]
### Tasks
- [ ] move tests off `default` namespace, to avoid collisions in parallel
- [ ] enable parallelization in each test
```

**Comment by gwynforthewyn** [comment]
I'd be up to take a shot at this! I found the tests in the workflow at https://github.com/kubernetes-sigs/blixt/actions/runs/6707983505/workflow#L40. I'll take a look over the weekend.

**Comment by shaneutt** [comment]
Awesome thank you! Please let us know if you need any help!

/assign @gwynforthewyn

**Comment by gwynforthewyn** [comment]
I've bitten off a bit more than I anticipated here! The approach I've taken so far is to add a call into the reflection API to interrogate the name of the test function, so that I can use the name of the test function as a unique namespace name; the diff is here: https://github.com/kubernetes-sigs/blixt/compare/main...gwynforthewyn:blixt:update-one-namespace?expand=1

What this has shown me so far:

* I need a way to create the test namespaces without code duplication. I anticipate I can actually do that inside the `testutils.NewTestNameSpace()` function
* The test themselves are a bit flaky on my system.
* I think I need a way to clean up the test namespace from the kind cluster. DO you have any opinions on that, @shaneutt ?  Can they be left around with the assumption that new kind clusters are created for every test run? Or should I be tidying up?

Thanks!

**Comment by shaneutt** [comment]
> I've bitten off a bit more than I anticipated here! The approach I've taken so far is to add a call into the reflection API to interrogate the name of the test function, so that I can use the name of the test function as a unique namespace name; the diff is here: https://github.com/kubernetes-sigs/blixt/compare/main...gwynforthewyn:blixt:update-one-namespace?expand=1
> 
> What this has shown me so far:
> 
>     * I need a way to create the test namespaces without code duplication. I anticipate I can actually do that inside the `testutils.NewTestNameSpace()` function

In the testing framework we're using, there is a `clusters.GenerateNamespace()` function that should be helpful in this regard.

>     * I think I need a way to clean up the test namespace from the kind cluster. DO you have any opinions on that, @shaneutt ?  Can they be left around with the assumption that new kind clusters are created for every test run? Or should I be tidying up?

If you use the `clusters.GenerateNamespace()` above, there's also a `clusters.NewCleaner()` in that same package, and you can feed the cleaner namespaces that need to be cleaned up with `cleaner.AddNamespace(ns)`, then you can ultimately just call `cleaner.Cleanup()` in a defer at the top of each test. Let us know if you run into any snags with that?

>     * The test themselves are a bit flaky on my system.

I've actually noticed some flakes since we moved the repo, when you run into them if you can spare the time to log information about them it would be appreciated, as we need to dig into these asap.

> Thanks!

No problem, thank you for taking this on and helping out we're glad to have you working on the project with us! :vulcan_salute:

**Comment by gwynforthewyn** [comment]
I just wanted to drop a note to say I'm still mindful of this; I'm just having a busy couple of weeks at work that I'm focusing on.

**Comment by shaneutt** [comment]
We recently decided to rewrite the control-plane in Rust (see https://github.com/kubernetes-sigs/blixt/milestone/8) so for the moment, this issue is out-of-date and we'll close it to avoid confusion.
