### ISSUE TITLE
Update README for how to deploy on local

### ISSUE THREAD

**Issue by Shunpoco** [kubernetes-sigs/blixt#175]
Hi communities! :wave: 

I'm very interested in this project, so I tried to deploy Blixt on my local Kind cluster today.
However, I got errors about pulling images from ghcr.io/kubernetes-sigs:
```bash
Warning  Failed     31s (x3 over 76s)  kubelet            Failed to pull image "ghcr.io/kubernetes-sigs/blixt-dataplane:latest": rpc error: code = Unknown desc = failed to pull and unpack image "ghcr.io/kubernetes-sigs/blixt-dataplane:latest": failed to resolve reference "ghcr.io/kubernetes-sigs/blixt-dataplane:latest": failed to authorize: failed to fetch anonymous token: unexpected status from GET request to https://ghcr.io/token?scope=repository%3Akubernetes-sigs%2Fblixt-dataplane%3Apull&service=ghcr.io: 401 Unauthorized
```

After several research, I found a way to solve the problem at https://github.com/kubernetes-sigs/blixt/issues/47.
Now I can deploy Blixt on my cluster by following the steps:
1. `make build.all.images` (as described in https://github.com/kubernetes-sigs/blixt/issues/47#issuecomment-1838654890)
2. `make load.all.images`
3. `kubectl apply -k ./config/tests/integration` (because those built images have a tag `integration-tests`)

I think we should add those steps to README.
I understand that the current situation (using ghcr.io) is temporary, but at the moment, writing the current deployment steps is very user-friendly, especially for newbies.

If those make sense for you, I will make a PR to modify README!

**Comment by shaneutt** [comment]
Thanks @Shunpoco,

Very glad to see your interest in the project, please do reach out to us if there's anything specific you're interested in, if you get stuck and need help, e.t.c.

Good call on the README, it's true that presently the ghcr.io images are not public due to policies about images in `kubernetes-sigs`, and we have an issue (#106) that tracks getting us moved over to an accepted registry. Please do feel free to update the README and add steps to the `# Usage` section, and thanks for taking the time to work through that and identify the problem!

Also note that the tag can be easily overridden, for instance:

```console
$ make build.all.images TAG=latest
$ make load.all.images TAG=latest
```

And then the standard `$ kubectl apply -f ./config/default` should then work.

**Comment by Shunpoco** [comment]
@shaneutt 
Thanks!

I will make a PR soon.

> Also note that the tag can be easily overridden, for instance:

I didn't know that. I will use it for my PR :smile:
